### ISSUE TITLE
Alien Swarm: Jastian Summer

### ISSUE THREAD

**Issue by BenLubar** [BenLubar/jastian-summer#1]
# Phase 1: Initial Planning

- [x] Decide [general plan](https://github.com/BenLubar/jastian-summer/blob/main/docs/brainstorming.txt) for missions (location/basic objective)
- [x] Name missions
- [ ] Write plan for how to get to release (#1)

# Phase 2: Scaffolding

- [x] Create campaign/mission definition files
- [x] Create vgui VMT files
- Create very rough mission layouts
    - [ ] jastian01_tharsis
    - [ ] bonus_jastian_tharsis + dm_jastian01_tharsis
    - [ ] jastian02_deepcore
    - [ ] jastian03_rata_terebro + dm_jastian02_rata_terebro
    - [ ] jastian04_cholistan
    - [ ] endless_jastian_cholistan + dm_jastian03_cholistan
    - [x] jastian05_inquest + endless_jastian_inquest + dm_jastian04_inquest
- Add rough objectives/logic entities to missions
    - [ ] bonus_jastian_tharsis
    - [ ] dm_jastian01_tharsis
    - [ ] dm_jastian02_rata_terebro
    - [ ] dm_jastian03_cholistan
    - [ ] dm_jastian04_inquest
    - [ ] endless_jastian_cholistan
    - [ ] endless_jastian_inquest
    - [ ] jastian01_tharsis
    - [ ] jastian02_deepcore
    - [ ] jastian03_rata_terebro
    - [ ] jastian04_cholistan
    - [ ] jastian05_inquest
- Write rough story summary
    - [x] bonus_jastian_tharsis
    - [ ] endless_jastian_cholistan
    - [ ] endless_jastian_inquest
    - [ ] jastian01_tharsis
    - [ ] jastian02_deepcore
    - [ ] jastian03_rata_terebro
    - [ ] jastian04_cholistan
    - [ ] jastian05_inquest

# Phase 3: Writing/Design

- [ ] Write mission descriptions
- [ ] Write objective text
- [ ] Write debriefings
- [ ] Determine what new textures are needed
- [ ] Determine which/when voiceovers will be used
- [ ] Create rough holdout mission script
- Less-rough mission layouts, determine placement of major props, etc.
    - [ ] jastian01_tharsis
    - [ ] bonus_jastian_tharsis + dm_jastian01_tharsis
    - [ ] jastian02_deepcore
    - [ ] jastian03_rata_terebro + dm_jastian02_rata_terebro
    - [ ] jastian04_cholistan
    - [ ] endless_jastian_cholistan + dm_jastian03_cholistan
    - [ ] jastian05_inquest + endless_jastian_inquest + dm_jastian04_inquest

# Phase 4: Detail

- Detail mission terrain, polish objectives, add soundscapes
    - [ ] bonus_jastian_tharsis
    - [ ] dm_jastian01_tharsis
    - [ ] dm_jastian02_rata_terebro
    - [ ] dm_jastian03_cholistan
    - [ ] dm_jastian04_inquest
    - [ ] endless_jastian_cholistan
    - [ ] endless_jastian_inquest
    - [ ] jastian01_tharsis
    - [ ] jastian02_deepcore
    - [ ] jastian03_rata_terebro
    - [ ] jastian04_cholistan
    - [ ] jastian05_inquest
- Mission icons
    - [ ] (campaign)
    - [ ] bonus_jastian_tharsis
    - [ ] dm_jastian01_tharsis
    - [ ] dm_jastian02_rata_terebro
    - [ ] dm_jastian03_cholistan
    - [ ] dm_jastian04_inquest
    - [ ] endless_jastian_cholistan
    - [ ] endless_jastian_inquest
    - [ ] jastian01_tharsis
    - [ ] jastian02_deepcore
    - [ ] jastian03_rata_terebro
    - [ ] jastian04_cholistan
    - [ ] jastian05_inquest
- Overview maps
    - [ ] bonus_jastian_tharsis
    - [ ] dm_jastian01_tharsis
    - [ ] dm_jastian02_rata_terebro
    - [ ] dm_jastian03_cholistan
    - [ ] dm_jastian04_inquest
    - [ ] endless_jastian_cholistan
    - [ ] endless_jastian_inquest
    - [ ] jastian01_tharsis
    - [ ] jastian02_deepcore
    - [ ] jastian03_rata_terebro
    - [ ] jastian04_cholistan
    - [ ] jastian05_inquest

# Phase 5: Polish

- [ ] Campaign map
- Add created textures
    - (pending phase 3)
- Add voice acting
    - (pending phase 3)
- Nodegraph
    - [ ] bonus_jastian_tharsis
    - [ ] dm_jastian01_tharsis
    - [ ] dm_jastian02_rata_terebro
    - [ ] dm_jastian03_cholistan
    - [ ] dm_jastian04_inquest
    - [ ] endless_jastian_cholistan
    - [ ] endless_jastian_inquest
    - [ ] jastian01_tharsis
    - [ ] jastian02_deepcore
    - [ ] jastian03_rata_terebro
    - [ ] jastian04_cholistan
    - [ ] jastian05_inquest
- Finalize spawning
    - [ ] bonus_jastian_tharsis
    - [ ] endless_jastian_cholistan
    - [ ] endless_jastian_inquest
    - [ ] jastian01_tharsis
    - [ ] jastian02_deepcore
    - [ ] jastian03_rata_terebro
    - [ ] jastian04_cholistan
    - [ ] jastian05_inquest

# Phase 6: Playtesting

- [ ] Limited Workshop release
- Playtest maps, record and iterate on feedback
    - [ ] bonus_jastian_tharsis
    - [ ] dm_jastian01_tharsis
    - [ ] dm_jastian02_rata_terebro
    - [ ] dm_jastian03_cholistan
    - [ ] dm_jastian04_inquest
    - [ ] endless_jastian_cholistan
    - [ ] endless_jastian_inquest
    - [ ] jastian01_tharsis
    - [ ] jastian02_deepcore
    - [ ] jastian03_rata_terebro
    - [ ] jastian04_cholistan
    - [ ] jastian05_inquest

# Phase 7: Release

- [ ] Write addon long description
- [ ] Create website
- [ ] Public Workshop release
